### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by majorization** [Brokenwind/BertSimilarity#17]
使用tf 2.5运行报错
ValueError: Tensor-typed variable initializers must either be wrapped in an init_scope or callable (e.g., `tf.Variable(lambda : tf.truncated_normal([10, 40]))`) when building functions. Please file a feature request if this restriction inconveniences you.

**Comment by Brokenwind** [comment]
目前是不支持 tensorflow 2的，切换到1.14左右的版本都应该OK

**Comment by majorization** [comment]
> 
> 
> 目前是不支持 tensorflow 2的，切换到1.14左右的版本都应该OK

好的，多谢。 tensorflow就是版本问题太头痛了。 换个版本需要解决一堆BUG。有些都不知道出在哪里

**Comment by majorization** [comment]
已经解决

**Comment by majorization** [comment]
。
